# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: imBryce.com
email: bryce.handerson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website, I have too many hobbies and not enough
  time to do any of them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imbryce.com" # the base hostname & protocol for your site
twitter_username: brycehanderson
github_username:  bhanderson

# Build settings
markdown: kramdown
